common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: mateo525

development:
  <<: *common
  database: susubank_development

test: &test
  <<: *common
  database: susubank_test

production:
  <<: *common
  database: susubank_production

